# Generated by Django 3.2.20 on 2023-08-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('github', models.CharField(default=None, max_length=200, null=True)),
                ('isOB', models.BooleanField(default=False)),
                ('currentCoin', models.IntegerField(default=0)),
                ('sumCoin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='애랑이')),
                ('exp', models.IntegerField(default=0)),
                ('rebirth', models.IntegerField(default=0)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('images', models.TextField(default='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='BoardLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='BoardImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='board')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member'),
        ),
    ]
